# Generated by Django 4.1 on 2023-05-28 14:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=30)),
                ('numlesson', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(default='New', max_length=10)),
                ('createdc', models.DateTimeField(auto_now=True)),
                ('updatedc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', ckeditor.fields.RichTextField()),
                ('icon', models.CharField(max_length=250)),
                ('video_url', models.CharField(max_length=250)),
                ('duration', models.IntegerField(help_text='min')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcources.modelcourse')),
            ],
        ),
    ]
